import { describe, it, expect } from "vitest";
import * as fc from "fast-check";

describe("list drafts property tests", () => {
  const draftArb = fc.record({
    id: fc.uuid(),
    content: fc.string({ minLength: 1 }),
    prompt: fc.string({ minLength: 1 }),
    status: fc.constantFrom("draft", "approved", "rejected"),
    createdBy: fc.string({ minLength: 1 }),
  });

  it("list of drafts should preserve all items", () => {
    fc.assert(
      fc.property(fc.array(draftArb), (drafts) => {
        const filtered = drafts.filter((d) => d.status === "draft");
        expect(filtered.length).toBeLessThanOrEqual(drafts.length);
      }),
    );
  });

  it("filtering by status should return correct subset", () => {
    fc.assert(
      fc.property(
        fc.array(draftArb, { minLength: 1 }),
        fc.constantFrom("draft", "approved", "rejected"),
        (drafts, status) => {
          const filtered = drafts.filter((d) => d.status === status);
          for (const d of filtered) {
            expect(d.status).toBe(status);
          }
        },
      ),
    );
  });

  it("all drafts should have unique ids", () => {
    fc.assert(
      fc.property(fc.array(draftArb, { minLength: 1 }), (drafts) => {
        const ids = drafts.map((d) => d.id);
        const uniqueIds = new Set(ids);
        // UUIDs generated by fast-check should be unique in practice
        expect(uniqueIds.size).toBe(ids.length);
      }),
    );
  });
});
